### ISSUE TITLE
lodash version issue

### ISSUE THREAD

**Issue by luoye-fe** [izaakschroeder/package-merge#5]
If there is no version of the `lodash` in `package.json`, it will use latest, `v4.0+` , but, this repo can  only use `v3.0+`. 

```
Error: Cannot find module 'lodash/object/mapValues'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/loye/Documents/coding/FET/cmd2app/node_modules/package-merge/lib/merge.js:5:17)
    at Module._compile (module.js:541:32)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/loye/Documents/coding/FET/cmd2app/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
```

**Comment by willkurk** [comment]
I am trying to use this project in along with other dependencies that require lodash 4.0+. 

I found it works with lodash 4+ after making these changes in merge.js: var mapValues = require('lodash/mapValues');
var assign = require('lodash/assign');
var isEmpty = require('lodash/isEmpty');
var filter = require('lodash/filter');
var contains = require('lodash/includes');
var has = require('lodash/has');

Is it possible we could update the repo to work with lodash version 4?

**Comment by willkurk** [comment]
Changing it to pull lodash v3+ instead of relying on the main lodash download would also work.

**Comment by goldingdamien** [comment]
Will this be fixed soon?

**Comment by willkurk** [comment]
I made this package with the issue fixed: https://www.npmjs.com/package/package-merge-lodash-4

**Comment by goldingdamien** [comment]
@willkurk Worked. Thanks.
